<<<<<<< HEAD
spring.application.name=ProductsMicroservice

server.port=0

spring.kafka.producer.bootstrap-server=localhost:9092,localhost:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


# waits for an acknowledgment from all the brokers
spring.kafka.producer.acks=all
# how many times the producer will try to send a message before making it as failed. default value is 2147483647
#spring.kafka.producer.retries=10
# how long the producer will wait before attempting to retry a failed request. default value is 100ms
#spring.kafka.producer.properties.retry.backoff.ms=1000

# the maximum time the producer can spend trying to deliver the message( deliver.timeout.ms >= linger.ms + request.timeout.ms)
spring.kafka.producer.properties.delivery.timeout.ms=120000

# The maximum time that the producer will wait and buffer the data before sending batch of messages. the default value is 0
spring.kafka.producer.properties.linger.ms=0
# The maximum time the producer will wait for a response from the broker after sending a request. the default value is 30000ms
spring.kafka.producer.properties.request.timeout.ms=30000


# It avoids the duplicate messages in the log in the presence of failures and retries
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.in.flight.request.pre.connection=5




=======
spring.application.name=EmailNotificationMicroservice
>>>>>>> 06368ff (Kakfa consumer)
